### ISSUE TITLE
Not working with Big Sur/latest homebrew version

### ISSUE THREAD

**Issue by enzodesena** [laurensk/logisim-macos#1]
Thanks for your work on this. In Big Sur 11.1 and Homebrew 2.7.1 (both the latest version available) the app does not seem to run, possibly because I can't install java with cask extension.  

More specifically, running ``brew cask install java`` gives the error ``Calling brew cask install is disabled! Use brew install [--cask] instead.``. 
Running ``brew install --cask java`` gives the error ``Cask 'java' is unavailable: No Cask with this name exists.``

Running ``brew install java`` only, and then running your app does not appear to be working since the gear symbol in the top-right corner disappears in a few seconds and then nothing happens.

**Comment by laurensk** [comment]
Thanks for your interest. Have you tried installing Java with `brew cask install adoptopenjdk8-openj9`?
It doesn't seem that macOS Big Sur nor my application stub is the problem here, I think the error comes from an incompatible version of Homebrew and Java.

**Comment by enzodesena** [comment]
Thanks a lot for the quick response! I am afraid that package is not available either. 

If I run ``brew cask install adoptopenjdk8-openj9`` I get: ``Calling brew cask install is disabled! Use brew install [--cask] instead.``.

If I run ``brew install --cask adoptopenjdk8-openj9`` I get the error: ``Cask 'adoptopenjdk8-openj9' is unavailable: No Cask with this name exists``.

**Comment by laurensk** [comment]
Can you try again with `brew install --cask adoptopenjdk/openjdk/adoptopenjdk8 `?

**Comment by enzodesena** [comment]
That worked!! Thanks so much!! Please let me know if you'd like me to edit the README and make a pull request.

**Comment by laurensk** [comment]
That would be awesome if you could do that! Please leave the "old" method in the readme too (for users with old versions of macOS and Homebrew).
